const question = [
	["What is the will of God?","Psalms 40:8","I delight to do thy will, O my God: Yea, thy law is within my heart."],
	["What is the will of God?","Hebrew 10:7","Then said I, Lo, I come (in the volume of the book it is written of me,) to do thy will, O God."],
	["What is the spirit?","John 6:63","It is the spirit that quickeneth; the flesh profiteth nothing: the words that I speak unto you, they are spirit, and they are life."],
	["What is water?","Ephisians 5:26","That he might sanctify and cleanse it with the washing of water by the word,"],
	["Who are the Saints?","Psalms 148:14","He also exalteth the horn of his people, The praise of all his saints; Even of the children of Israel, a people near unto him. Praise ye the LORD."],
	["Who is the world?","Isaiah 45:17","But Israel shall be saved by the LORD With an everlasting salvation; You shall not be ashamed or disgraced Forever and ever."],
	["Is Color in the Bible?","Daniel 10:5-6","Then I lifted up mine eyes, and looked, and behold a certain man clothed in linen, whose loins were girded with fine gold of Uphaz: 6His body also was like the beryl, and his face as the appearance of lightning, and his eyes as lamps of fire, and his arms and his feet like in colour to polished brass, and the voice of his words like the voice of a multitude."],
	["Is Color in the Bible?","Revelation 1:14-15","1His head and his hairs were white like wool, as white as snow; and his eyes were as a flame of fire And his feet like unto fine brass, as if they burned in a furnace; and his voice as the sound of many waters."],
	["Is Color in the Bible?","Revelation 2:18","And unto the angel of the church in Thyatira write; These things saith the Son of God, who hath his eyes like unto a flame of fire, and his feet are like fine brass"],
	["What is the word of God?","Isaiah 8:20","To the law and to the testimony: if they speak not according to this word, it is because there is no light in them."],
	["What is light?","Proverbs 6:23","For the commandment is a lamp; and the law is light; and reproofs of instruction are the way of life:"],
	["What is light?","Psalms 119:105","Thy word is a lamp unto my feet, and a light unto my path."],
	["Why can't women wear pants?","Deuteronomy 22:5","The woman shall not wear that which pertaineth unto a man, neither shall a man put on a woman's garment: for all that do so are abomination unto."],
	["God is a spirit he has no body?","Daniel 7:9","I beheld till the thrones were cast down, and the Ancient of days did sit, whose garment was white as snow, and the hair of his head like the pure."],
	["God is a spirit he has no body?","Exodus 33:18-23","And he said, I beseech thee, shew me thy glory. And he said, I will make all my goodness pass before thee, and I will proclaim the name of the Lord before thee; and will be gracious to whom I will be gracious, and will shew mercy on whom I will shew mercy.And he said, Thou canst not see my face: for there shall no man see me, and live. And the Lord said, Behold, there is a place by me, and thou shalt stand upon a rock. And it shall come to pass, while my glory passeth by, that I will put thee in a clift of the rock, and will cover thee with my hand while I pass by. And I will take away mine hand, and thou shalt see my back parts: but my face shall not be seen."],
	["God is a spirit he has no body?","1 Corithians 15:44","it is sown a natural body; it is raised a spiritual body. There is a natural body, and there is a spiritual body."],
	["Who is the firstborn?","Exodus 4:22","And thou shalt say unto Pharaoh, Thus saith the LORD, Israel is my son, even my firstborn"],
	["How does God plead?","Isaiah 66:15-16","For, behold, the Lord will come with fire, and with his chariots like a whirlwind, to render his anger with fury, and his rebuke with flames of fire. For by fire and by his sword will the Lord plead with all flesh: and the slain of the Lord shall be many."],
	["Who or what is the Olive tree?","Jeremiah 11:16","The LORD called thy name, A green olive tree, fair, and of goodly fruit: with the noise of a great tumult he hath kindled fire upon it, and the branches of it are broken."],
	["What is Comfort?","Psalms 119:50","This is my comfort in my affliction: for thy word hath quickened me."],
	["What is Comfort?","Romans 15:4","For whatsoever things were written aforetime were written for our learning, that we through patience and comfort of the scriptures might have hope."],
	["America is spiritual Babylon?","Psalms 137:7","Remember, O LORD, the children of Edom in the day of Jerusalem; who said, Rase it, rase it, even to the foundation thereof."],
	["Who are the beloved?","Jeremiah 12:7-8","I have forsaken mine house, I have left mine heritage I have given the dearly beloved of my soul into the hand of her enemies. Mine heritage is unto me as a lion in the forest; it crieth out against me: therefore have I hated it."],
	["Who are the beloved?","Jeremiah 11:15-16","What hath my beloved to do in mine house, seeing she hath wrought lewdness with many, and the holy flesh is passed from thee? when thou doest evil, then thou rejoicest. The Lord called thy name, A green olive tree, fair, and of goodly fruit: with the noise of a great tumult he hath kindled fire upon it, and the branches of it are broken."],
	["For who is grace?","Zechariah 12:10","And I will pour upon the house of David, and upon the inhabitants of Jerusalem, the spirit of grace and of supplications: and they shall look upon me whom they have pierced, and they shall mourn for him, as one mourneth for his only son, and shall be in bitterness for him, as one that is in bitterness for his firstborn."],
	["What tribe is Christ from?","Hebrew 7:14","For it is evident that our Lord sprang out of Juda; of which tribe Moses spake nothing concerning priesthood."],
	["Who are the justified?","Isaiah 45:25","In the LORD shall all the seed of Israel be justified, and shall glory."],
	["For who is redemption?","Psalms130:7-8","Let Israel hope in the Lord: for with the Lord there is mercy, and with him is plenteous redemption. And he shall redeem Israel from all his iniquities."],
	["Our rightousness?","Deuteronomy 6:25","And it shall be our righteousness, if we observe to do all these commandments before the LORD our God, as he hath commanded us."],
	["Who is the top witness? Christ","Isaiah 55:4","Behold, I have given him for a witness to the people, a leader and commander to the people."],
	["Who is the top witness? Christ","Revelation 1:5","And from Jesus Christ, who is the faithful witness, and the first begotten of the dead, and the prince of the kings of the earth."],
	["Who is Gods witness?","Isaiah 44:8","Fear ye not, neither be afraid: have not I told thee from that time, and have declared it? ye are even my witnesses. Is there a God beside me? yea, there is no God; I know not any."],
	["Who is Gods witness?","Isaiah 43:10","Ye are my witnesses, saith the LORD, and my servant whom I have chosen: that ye may know and believe me, and understand that I am he: before me there was no God formed, neither shall there be after me."],
	["Who is Gods witness?","Joshua 24:22","And Joshua said unto the people, Ye are witnesses against yourselves that ye have chosen you the LORD, to serve him. And they said, We are witnesses."],
	["Who are the Elect","Isaiah 45:4","For Jacob my servant's sake, and Israel mine elect, I have even called thee by thy name: I have surnamed thee, though thou hast not known me."],
	["Who are Gods Servants?","Leviticus 25:55","For unto me the children of Israel are servants; they are my servants whom I brought forth out of the land of Egypt: I am the LORD your God."],
	["Who are Gods Servants?","Isaiah 44:1","Yet now hear, O Jacob my servant; and Israel, whom I have chosen:"],
	["Who are Gods Servants?","Isaiah 44:21","Remember these, O Jacob and Israel; for thou art my servant: I have formed thee; thou art my servant: O Israel, thou shalt not be forgotten of me."],
	["Who are Gods Servants?","Isaiah 49:3","And said unto me, Thou art my servant, O Israel, in whom I will be glorified."],
	["How must the bible be read?","Isaiah 28:10","For precept must be upon precept, precept upon precept; line upon line, line upon line; here a little, and there a little"],
	["What is Sin?","1 John 3:4","Whosoever committeth sin transgresseth also the law: for sin is the transgression of the law."],
	["What is truth?","Psalms 119:142","Thy righteousness is an everlasting righteousness, and thy law is the truth."],
	["What is truth?","John 17:17","Sanctify them through thy truth: thy word is truth."],
	["What is truth?","John 8:32","And ye shall know the truth, and the truth shall make you free."],
	["What is truth?","John 14:6","Jesus saith unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me."],
	["What is truth?","Psalms 119:151","Thou art near, O LORD; and all thy commandments are truth."],
	["What is Knowledge?","Malachi 2:7","For the priest's lips should keep knowledge, and they should seek the law at his mouth: for he is the messenger of the LORD of hosts."],
	["What is Knowledge?","Proverbs 1:7","The fear of the LORD is the beginning of knowledge: but fools despise wisdom and instruction."],
	["Speak in tongues?","Isaiah 28:11","For with stammering lips and another tongue will he speak to this people."],
	["Speak in tongues?","Acts 2:1-4","And when the day of Pentecost was fully come, they were all with one accord in one place. 2 And suddenly there came a sound from heaven as of a rushing mighty wind, and it filled all the house where they were sitting. And there appeared unto them cloven tongues like as of fire, and it sat upon each of them. And they were all filled with the Holy Ghost, and began to speak with other tongues, as the Spirit gave them utterance."],
	["Speak in tongues?","1 Corithians 14:21","In the law it is written, With men of other tongues and other lips will I speak unto this people; and yet for all that will they not hear me, saith the Lord."],
	["D1","D2","D3"],
	];



question1 = question.slice(0).sort();
quest = question.sort(() => Math.random() - 0.5);


